site_name: 'python-app'
site_description: 'Main docs for the Python App'
repo_url: https://github.com/loickreitmann/python-app
edit_uri: edit/main/docs
plugins:
  - techdocs-core
nav:
  - Peomes:
    - Apollinaire: 'poems/apollinaire.md'