redis-ha:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1

global:
  domain: argocd-server.local

certificate:
  enabled: true

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd-server.local
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    tls: true
    tlsSecretName: argocd-server-tls